SET SCHEMA FN72OO3;

CREATE TABLE HOTEL(

    NAME VARCHAR(20) NOT NULL ,
    LOCATION VARCHAR(15) NOT NULL ,
    PARKING INT,
    SWIMMINGPOOL INT,
    FITNESS INT,
    WIFI INT,
    SPA INT,
    ROOMSERVICE INT,
    RESTAURANT INT,
    CONSTRAINT CK_PARKING CHECK (PARKING = 0 OR PARKING = 1),
    CONSTRAINT CK_SWIMMING_POOL CHECK (SWIMMINGPOOL = 0 OR SWIMMINGPOOL = 1),
    CONSTRAINT CK_FITNESS CHECK (FITNESS = 0 OR FITNESS = 1),
    CONSTRAINT CK_WIFI CHECK (WIFI = 0 OR WIFI = 1),
    CONSTRAINT CK_SPA CHECK (SPA = 0 OR SPA = 1),
    CONSTRAINT CK_ROOM_SERVICE CHECK (ROOMSERVICE = 0 OR ROOMSERVICE = 1),
    CONSTRAINT CK_RESTAURANT CHECK (RESTAURANT = 0 OR RESTAURANT = 1),
    CONSTRAINT PK_HOTEL_INFO PRIMARY KEY (NAME,LOCATION)
);

CREATE TABLE HOTELSTAFF(
 STAFFID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH  1 INCREMENT BY 1),
 NAME VARCHAR(10) NOT NULL ,
 TELNUMBER VARCHAR(10) NOT NULL,
 HOTELNAME VARCHAR(20) NOT NULL ,
 HOTELLOC VARCHAR(15) NOT NULL,
 FOREIGN KEY FK_WORKS_AT (HOTELNAME,HOTELLOC) REFERENCES HOTEL(NAME,LOCATION),
 PRIMARY KEY (STAFFID)
);

CREATE TABLE CLIENT(
    PIN CHAR(10) NOT NULL PRIMARY KEY,
    NAME VARCHAR(15) NOT NULL ,
    TELNUMBER CHAR(10)
);

CREATE TABLE ROOM(
    HOTEL VARCHAR(20) NOT NULL ,
    HOTELLOC VARCHAR(15) NOT NULL,
    TYPE VARCHAR(6),
    FLOOR INT NOT NULL,
    ROOMNUMBER INT NOT NULL,
    HASBALCONY INT,
    HASBATHTUB INT,
    STATUS VARCHAR(5) DEFAULT 'FREE',
    FOREIGN KEY FK_HOTEL_INFO(HOTEL,HOTELLOC) REFERENCES HOTEL(NAME,LOCATION),
    CONSTRAINT CK_ROOM_TYPE CHECK ( TYPE = 'SINGLE' OR TYPE = 'DOUBLE' OR TYPE = 'TRIPLE' OR TYPE = 'QUAD' ),
    CONSTRAINT CK_ROOM_FLOOR CHECK (FLOOR > 0),
    CONSTRAINT CK_ROOM_NUMBER CHECK (ROOMNUMBER > 0),
    CONSTRAINT CK_HAS_BALCONY CHECK (HASBALCONY = 0 OR HASBALCONY = 1),
    CONSTRAINT CK_HAS_BATH_TUB CHECK (HASBATHTUB = 0 OR HASBATHTUB = 1),
    CONSTRAINT CK_STATUS CHECK ( STATUS = 'FREE' OR STATUS = 'TAKEN' ),
    CONSTRAINT PK_ROOM_INFO PRIMARY KEY (HOTEL, HOTELLOC,FLOOR,ROOMNUMBER)
);

CREATE TABLE RESERVATION(
    HOTEL VARCHAR(20),
    LOCATION VARCHAR(15),
    CLIENTPIN CHAR(10),
    ROOMTYPE VARCHAR(6),
    FLOOR INT,
    NUMBER INT,
    RESERVATIONID INT NOT NULL GENERATED AS IDENTITY (START WITH  72003 INCREMENT BY 1) PRIMARY KEY,
    ACCOM DATE,
    RELEASE DATE,
    INITIALPRICE DOUBLE,
    EXTRAPRICE DOUBLE,
    USESROOMSERVICE INT,
    USESSPA INT,
    USESPARKING INT,
    FOREIGN KEY FK_RESERVATION_INFO(HOTEL,LOCATION,FLOOR,NUMBER) REFERENCES FN72OO3.ROOM(HOTEL,HOTELLOC,FLOOR,ROOMNUMBER),
    FOREIGN KEY FK_CLIENT_INFO (CLIENTPIN) REFERENCES CLIENT(PIN),
    CONSTRAINT CK_RESERVATION_DATE CHECK ( RESERVATION.ACCOM < RESERVATION.RELEASE ),
    CONSTRAINT CK_INITIAL_PRICE CHECK ( INITIALPRICE > 0.0 ),
    CONSTRAINT CK_EXTRA_PRICE CHECK ( EXTRAPRICE >= 0.0 ),
    CONSTRAINT CK_USES_SPA CHECK (USESSPA = 0 OR USESSPA = 1),
    CONSTRAINT CK_USES_PARKING CHECK (USESPARKING = 0 OR USESPARKING = 1 ),
    CONSTRAINT CK_USES_ROOMSERVICE CHECK (USESROOMSERVICE = 0 OR USESROOMSERVICE = 1)
);
