SET SCHEMA FN72003;

CREATE VIEW ROOMS(
    NAME, STATUS , TYPE, FLOOR, NUMBER
    )AS
SELECT R.HOTEL,R.STATUS,R.TYPE,R.FLOOR,R.ROOMNUMBER
FROM FN72OO3.ROOM R
WHERE R.STATUS = 'FREE';

CREATE VIEW HAS_PARKING(
    NAME,LOCATION
    )AS
SELECT H.NAME,H.LOCATION
FROM FN72OO3.HOTEL H
WHERE H.PARKING = 1;